// src/access-control/presentation/components/rfid-encoder-panel/rfid-encoder-panel.component.ts
import {
  afterNextRender,
  Component,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MessageComponent } from '../../../../shared/presentation/components/message/message.component';
import { I18nService } from '../../../../shared/presentation/i18n.service';
import { AccessControlStore } from '../../../application/access-control.store';

/**
 * State of the front desk RFID encoder, with the action to encode a new card.
 * It emits the card ID once the card is written.
 */
@Component({
  selector: 'app-rfid-encoder-panel',
  imports: [
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MessageComponent,
  ],
  template: `
    <div class="flex flex-column gap-3">
      <div
        class="flex align-items-center gap-3 p-3 surface-card border-1 surface-border border-round-lg"
        aria-live="polite"
      >
        <span
          class="flex align-items-center justify-content-center w-2rem h-2rem flex-shrink-0 bg-primary-50 text-primary border-round-lg"
          aria-hidden="true"
          ><mat-icon>contactless</mat-icon></span
        >
        <span class="flex flex-column flex-1 min-w-0">
          <span class="font-semibold">{{
            i18n.t('access-control.rfid-encoder-panel.device')
          }}</span>
          <span class="text-sm text-color-secondary">{{
            i18n.t(
              'access-control.rfid-encoder-panel.states.' + store.encoderState()
            )
          }}</span>
        </span>
        <span class="flex align-items-center gap-2 text-sm font-medium">
          <span
            class="inline-block border-circle"
            [class]="stateAppearance()"
            style="width: 0.5rem; height: 0.5rem"
            aria-hidden="true"
          ></span>
          {{
            i18n.t(
              'access-control.rfid-encoder-panel.labels.' + store.encoderState()
            )
          }}
        </span>
      </div>
      @if (failed()) {
        <app-message severity="error">
          <div class="flex flex-column gap-1">
            <span class="font-semibold">{{
              i18n.t('access-control.rfid-encoder-panel.failed-title')
            }}</span>
            <span>{{
              i18n.t('access-control.rfid-encoder-panel.failed-text')
            }}</span>
          </div>
        </app-message>
      }
      @if (showAction()) {
        <button
          mat-flat-button
          type="button"
          class="w-full"
          [disabled]="disabled() || busy()"
          (click)="encode()"
        >
          @if (busy()) {
            <mat-spinner diameter="18" />
          } @else {
            <mat-icon>contactless</mat-icon>
          }
          {{
            actionLabel() || i18n.t('access-control.rfid-encoder-panel.encode')
          }}
        </button>
      }
    </div>
  `,
})
export class RfidEncoderPanelComponent {
  protected readonly i18n = inject(I18nService);
  protected readonly store = inject(AccessControlStore);

  /** Hides the encode button when another action, such as Replace, starts the encoding. */
  readonly showAction = input(true);
  /** Label of the encode button. */
  readonly actionLabel = input('');
  /** Whether the encode button is disabled. */
  readonly disabled = input(false);
  /** Emits the card ID of a newly encoded card. */
  readonly encoded = output<string>();

  protected readonly failed = computed(
    () => this.store.encoderState() === 'failed',
  );
  protected readonly busy = computed(() =>
    ['encoding', 'verifying'].includes(this.store.encoderState()),
  );
  protected readonly stateAppearance = computed(
    () =>
      ({
        ready: 'bg-green-500',
        encoding: 'bg-orange-500',
        verifying: 'bg-orange-500',
        encoded: 'bg-green-500',
        failed: 'bg-red-500',
      })[this.store.encoderState()],
  );

  constructor() {
    // A new panel starts with the encoder ready, as on mount in the Vue version.
    afterNextRender(() => this.store.resetEncoder());
  }

  /** Encodes a new card and emits its ID. */
  protected async encode(): Promise<void> {
    try {
      this.encoded.emit(await this.store.encodeKeyCard());
    } catch {
      // The encoder state shows the failure and the button allows a retry.
    }
  }
}

// src/access-control/presentation/components/rfid-encoder-panel.vue
<script setup>
import { computed, onMounted, toRefs } from 'vue';
import { useI18n } from 'vue-i18n';
import useAccessControlStore from '../../application/access-control.store.js';

defineProps({
  // Hides the encode button when another action, such as Replace, starts the encoding.
  showAction: { type: Boolean, default: true },
  actionLabel: { type: String, default: '' },
  disabled: { type: Boolean, default: false },
});
const emit = defineEmits(['encoded']);

const { t } = useI18n();
const store = useAccessControlStore();
const { encoderState } = toRefs(store);
const { encodeKeyCard, resetEncoder } = store;

const failed = computed(() => encoderState.value === 'failed');
const busy = computed(() =>
  ['encoding', 'verifying'].includes(encoderState.value),
);
const stateAppearance = computed(
  () =>
    ({
      ready: 'bg-green-500',
      encoding: 'bg-orange-500',
      verifying: 'bg-orange-500',
      encoded: 'bg-green-500',
      failed: 'bg-red-500',
    })[encoderState.value],
);

onMounted(resetEncoder);

/**
 * Writes a key card on the encoder and reports its card ID.
 */
const encode = async () => {
  try {
    emit('encoded', await encodeKeyCard());
  } catch {
    // The encoder state shows the failure and the button allows a retry.
  }
};
</script>

<template>
  <div class="flex flex-column gap-3">
    <div
      class="flex align-items-center gap-3 p-3 surface-card border-1 surface-border border-round-lg"
      aria-live="polite"
    >
      <pv-avatar
        icon="pi pi-wifi"
        shape="square"
        class="flex-shrink-0 bg-primary-50 text-primary border-round-lg"
        aria-hidden="true"
      />
      <span class="flex flex-column flex-1 min-w-0">
        <span class="font-semibold">{{
          t('access-control.rfid-encoder-panel.device')
        }}</span>
        <span class="text-sm text-color-secondary">{{
          t(`access-control.rfid-encoder-panel.states.${encoderState}`)
        }}</span>
      </span>
      <span class="flex align-items-center gap-2 text-sm font-medium">
        <span
          :class="['inline-block border-circle', stateAppearance]"
          style="width: 0.5rem; height: 0.5rem"
          aria-hidden="true"
        />
        {{ t(`access-control.rfid-encoder-panel.labels.${encoderState}`) }}
      </span>
    </div>
    <pv-message v-if="failed" severity="error" icon="pi pi-exclamation-circle">
      <div class="flex flex-column gap-1">
        <span class="font-semibold">{{
          t('access-control.rfid-encoder-panel.failed-title')
        }}</span>
        <span>{{ t('access-control.rfid-encoder-panel.failed-text') }}</span>
      </div>
    </pv-message>
    <pv-button
      v-if="showAction"
      :label="actionLabel || t('access-control.rfid-encoder-panel.encode')"
      icon="pi pi-wifi"
      rounded
      :loading="busy"
      :disabled="disabled || busy"
      @click="encode"
    />
  </div>
</template>
