// src/inventory/presentation/components/inventory-layout/inventory-layout.component.ts
import { Component, computed, contentChild, inject } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatTabsModule } from '@angular/material/tabs';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { ContextLayoutComponent } from '../../../../shared/presentation/components/context-layout/context-layout.component';
import { LayoutBodyDirective } from '../../../../shared/presentation/components/context-layout/layout-body.directive';
import { I18nService } from '../../../../shared/presentation/i18n.service';
import { InventoryStore } from '../../../application/inventory.store';

/**
 * Inventory workspace layout: header with the property selector, tabs for inventory items
 * and storage locations, and the loading and error states of the inventory data.
 */
@Component({
  selector: 'app-inventory-layout',
  imports: [
    ContextLayoutComponent,
    MatIconModule,
    MatTabsModule,
    RouterLink,
    RouterLinkActive,
  ],
  template: `
    <app-context-layout
      [title]="i18n.t('inventory.inventory-layout.title')"
      [properties]="store.properties()"
      [currentPropertyId]="store.currentPropertyId()"
      [propertyLabel]="i18n.t('inventory.inventory-layout.property')"
      [propertyDisabled]="store.saving()"
      [noProperties]="noProperties()"
      [noPropertiesMessage]="
        i18n.t('inventory.inventory-terms.errors.no-properties')
      "
      [failed]="store.errors().length > 0"
      [connectionMessage]="
        i18n.t('inventory.inventory-terms.errors.connection')
      "
      [retryLabel]="i18n.t('inventory.inventory-layout.retry')"
      [loaded]="inventoryLoaded()"
      [loadingLabel]="i18n.t('inventory.inventory-layout.loading')"
      [body]="body()?.template"
      (propertyChange)="changeProperty($event)"
      (retry)="retry()"
    >
      <ng-container ngProjectAs="[layoutActions]"
        ><ng-content select="[layoutActions]"
      /></ng-container>
      <nav
        layoutTabs
        mat-tab-nav-bar
        mat-stretch-tabs="false"
        [tabPanel]="tabPanel"
      >
        @for (tab of tabs; track tab.link) {
          <a
            mat-tab-link
            [routerLink]="tab.link"
            routerLinkActive
            #active="routerLinkActive"
            [active]="active.isActive"
          >
            <mat-icon class="mr-2" aria-hidden="true">{{ tab.icon }}</mat-icon>
            {{ i18n.t(tab.label) }}
          </a>
        }
      </nav>
      <mat-tab-nav-panel #tabPanel class="hidden" />
    </app-context-layout>
  `,
})
export class InventoryLayoutComponent {
  protected readonly i18n = inject(I18nService);
  protected readonly store = inject(InventoryStore);
  private readonly router = inject(Router);
  protected readonly body = contentChild(LayoutBodyDirective);

  protected readonly tabs = [
    {
      link: '/inventory/items',
      label: 'inventory.inventory-layout.inventory-items',
      icon: 'inventory_2',
    },
    {
      link: '/inventory/storage-locations',
      label: 'inventory.inventory-layout.storage-locations',
      icon: 'apartment',
    },
  ];

  protected readonly noProperties = computed(
    () => this.store.propertiesLoaded() && !this.store.properties().length,
  );
  protected readonly inventoryLoaded = computed(
    () =>
      this.store.inventoryItemsLoaded() && this.store.storageLocationsLoaded(),
  );

  constructor() {
    if (!this.store.propertiesLoaded()) this.store.fetchProperties();
  }

  /**
   * Navigates to the active tab and loads the selected property's inventory.
   * @param propertyId - The ID of the selected property.
   */
  protected async changeProperty(propertyId: number): Promise<void> {
    const activeTab = this.router.url.startsWith('/inventory/storage-location')
      ? '/inventory/storage-locations'
      : '/inventory/items';
    await this.router.navigateByUrl(activeTab);
    this.store.selectProperty(propertyId);
  }

  /** Retries loading the properties or the current property's inventory. */
  protected retry(): void {
    if (this.store.propertiesLoaded())
      this.store.selectProperty(this.store.currentPropertyId());
    else this.store.fetchProperties();
  }
}

// src/inventory/presentation/components/inventory-layout.vue
<script setup>
import { computed, onMounted, toRefs } from 'vue';
import { useI18n } from 'vue-i18n';
import { RouterLink, useRoute, useRouter } from 'vue-router';
import useInventoryStore from '../../application/inventory.store.js';
import SidebarToggle from '../../../shared/presentation/components/sidebar-toggle.vue';

const { t } = useI18n();
const route = useRoute();
const router = useRouter();
const store = useInventoryStore();
const {
  properties,
  propertiesLoaded,
  currentPropertyId,
  inventoryItemsLoaded,
  storageLocationsLoaded,
  errors,
  saving,
} = toRefs(store);
const { fetchProperties, selectProperty } = store;

const tabs = [
  {
    value: 'inventory-items',
    label: 'inventory.inventory-layout.inventory-items',
    icon: 'pi pi-box',
  },
  {
    value: 'inventory-storage-locations',
    label: 'inventory.inventory-layout.storage-locations',
    icon: 'pi pi-building',
  },
];
const activeTab = computed(() =>
  route.name?.startsWith('inventory-storage-location')
    ? 'inventory-storage-locations'
    : 'inventory-items',
);
const noProperties = computed(
  () => propertiesLoaded.value && !properties.value.length,
);
const inventoryLoaded = computed(
  () => inventoryItemsLoaded.value && storageLocationsLoaded.value,
);

onMounted(() => {
  if (!store.propertiesLoaded) fetchProperties();
});

/**
 * Navigates to the active tab's list and loads the selected property's inventory.
 * @param {number} propertyId - The ID of the selected property.
 */
const changeProperty = async (propertyId) => {
  await router.push({ name: activeTab.value });
  selectProperty(propertyId);
};

/**
 * Retries loading the properties or the current property's inventory.
 */
const retry = () => {
  if (propertiesLoaded.value) selectProperty(currentPropertyId.value);
  else fetchProperties();
};
</script>

<template>
  <div class="flex flex-column">
    <header
      class="sticky top-0 z-2 flex flex-wrap align-items-center gap-2 px-3 md:px-5 py-2 md:h-4rem surface-card border-bottom-1 surface-border"
    >
      <sidebar-toggle />
      <pv-divider layout="vertical" class="h-1rem min-h-0 p-0 mx-1 my-0" />
      <h1
        class="m-0 mr-auto text-xl font-semibold tracking-tight white-space-nowrap"
      >
        {{ t('inventory.inventory-layout.title') }}
      </h1>
      <pv-select
        :model-value="currentPropertyId"
        :options="properties"
        option-label="name"
        option-value="id"
        :aria-label="t('inventory.inventory-layout.property')"
        :disabled="saving"
        size="small"
        class="flex-order-1 md:flex-order-0 w-full md:w-14rem"
        @update:model-value="changeProperty"
      >
        <template #value="{ value }">
          <span class="flex align-items-center gap-2">
            <i class="pi pi-building text-color-secondary" aria-hidden="true" />
            <span
              class="font-medium white-space-nowrap overflow-hidden text-overflow-ellipsis"
              >{{
                properties.find((property) => property.id === value)?.name ??
                '—'
              }}</span
            >
          </span>
        </template>
      </pv-select>
      <slot name="actions" />
    </header>

    <div class="flex flex-column gap-4 p-3 md:px-5 md:pt-4 md:pb-5">
      <pv-tabs :value="activeTab">
        <pv-tab-list>
          <pv-tab
            v-for="tab in tabs"
            :key="tab.value"
            :value="tab.value"
            :as="RouterLink"
            :to="{ name: tab.value }"
            class="flex align-items-center gap-2"
          >
            <i :class="tab.icon" aria-hidden="true" />
            <span>{{ t(tab.label) }}</span>
          </pv-tab>
        </pv-tab-list>
      </pv-tabs>

      <pv-message v-if="noProperties" severity="warn" icon="pi pi-info-circle">
        {{ t('inventory.inventory-terms.errors.no-properties') }}
      </pv-message>
      <pv-message
        v-else-if="errors.length && !inventoryLoaded"
        severity="error"
        icon="pi pi-exclamation-circle"
      >
        <div
          class="flex flex-column sm:flex-row sm:align-items-center justify-content-between gap-3"
        >
          <span>{{ t('inventory.inventory-terms.errors.connection') }}</span>
          <pv-button
            :label="t('inventory.inventory-layout.retry')"
            icon="pi pi-refresh"
            severity="danger"
            size="small"
            @click="retry"
          />
        </div>
      </pv-message>
      <div
        v-else-if="!inventoryLoaded"
        class="flex flex-column align-items-center gap-3 py-8 text-color-secondary"
        role="status"
      >
        <pv-progress-spinner
          :stroke-width="4"
          class="w-3rem h-3rem"
          aria-hidden="true"
        />
        <span>{{ t('inventory.inventory-layout.loading') }}</span>
      </div>
      <slot v-else />
    </div>
  </div>
</template>
