// src/overview/presentation/components/booking-search/booking-search.component.ts
import {
  Component,
  ElementRef,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import {
  MatAutocompleteModule,
  MatAutocompleteSelectedEvent,
} from '@angular/material/autocomplete';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { Router } from '@angular/router';
import { BookingStatusTagComponent } from '../../../../bookings/presentation/components/booking-status-tag/booking-status-tag.component';
import { Booking } from '../../../../bookings/domain/model/booking.entity';
import { formatDayRange } from '../../../../shared/presentation/calendar-format';
import { I18nService } from '../../../../shared/presentation/i18n.service';
import { OverviewStore } from '../../../application/overview.store';

/** Search of the current property's bookings by guest or code, focused with Ctrl+K or ⌘K. */
@Component({
  selector: 'app-booking-search',
  imports: [
    MatAutocompleteModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    BookingStatusTagComponent,
  ],
  host: { '(window:keydown)': 'focusSearch($event)' },
  template: `
    <mat-form-field class="w-full" subscriptSizing="dynamic">
      <mat-icon matPrefix aria-hidden="true">search</mat-icon>
      <input
        #input
        matInput
        type="search"
        [value]="query()"
        [placeholder]="
          i18n.t('overview.booking-search.placeholder', { shortcut })
        "
        [attr.aria-label]="i18n.t('overview.booking-search.label')"
        [matAutocomplete]="auto"
        (input)="complete(input.value)"
      />
      <mat-autocomplete
        #auto="matAutocomplete"
        [displayWith]="displayNothing"
        panelWidth="24rem"
        (optionSelected)="openBooking($event)"
      >
        @for (booking of suggestions(); track booking.id) {
          <mat-option [value]="booking">
            <span
              class="flex align-items-center justify-content-between gap-3 w-full py-1"
            >
              <span class="flex flex-column min-w-0">
                <span class="font-semibold">{{ booking.guestName }}</span>
                <span class="text-sm text-color-secondary"
                  ><span class="font-mono">{{ booking.code }}</span> ·
                  {{ stay(booking) }}</span
                >
              </span>
              <app-booking-status-tag [status]="booking.status" />
            </span>
          </mat-option>
        } @empty {
          @if (query().trim()) {
            <mat-option disabled>{{
              i18n.t('overview.booking-search.empty')
            }}</mat-option>
          }
        }
      </mat-autocomplete>
    </mat-form-field>
  `,
  styles: `
    :host {
      display: block;
    }
  `,
})
export class BookingSearchComponent {
  protected readonly i18n = inject(I18nService);
  private readonly store = inject(OverviewStore);
  private readonly router = inject(Router);
  private readonly input =
    viewChild.required<ElementRef<HTMLInputElement>>('input');

  protected readonly query = signal('');
  protected readonly suggestions = signal<Booking[]>([]);
  /** Keeps the input empty once a booking is chosen. */
  protected readonly displayNothing = () => '';
  protected readonly shortcut = /Mac|iPhone|iPad/.test(navigator.platform)
    ? '⌘K'
    : 'Ctrl+K';

  /**
   * Updates the suggestions for the typed text.
   * @param text - Typed text.
   */
  protected complete(text: string): void {
    this.query.set(text);
    this.suggestions.set(this.store.searchBookings(text));
  }

  /**
   * Opens the chosen booking and clears the search.
   * @param event - Autocomplete selection event.
   */
  protected openBooking(event: MatAutocompleteSelectedEvent): void {
    const booking = event.option.value as Booking;
    this.query.set('');
    this.suggestions.set([]);
    this.input().nativeElement.value = '';
    this.input().nativeElement.blur();
    this.router.navigate(['/bookings', booking.id]);
  }

  /**
   * Focuses the search with Ctrl+K or ⌘K.
   * @param event - Key event.
   */
  protected focusSearch(event: KeyboardEvent): void {
    if (event.key?.toLowerCase() === 'k' && (event.metaKey || event.ctrlKey)) {
      event.preventDefault();
      this.input().nativeElement.focus();
    }
  }

  /** @returns Stay dates of a booking in the active locale. */
  protected stay(booking: Booking): string {
    return formatDayRange(
      booking.checkInDate,
      booking.checkOutDate,
      this.i18n.locale(),
    );
  }
}

// src/overview/presentation/components/booking-search.vue
<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRouter } from 'vue-router';
import useOverviewStore from '../../application/overview.store.js';
import { formatDayRange } from '../../../shared/presentation/calendar-format.js';
import BookingStatusTag from '../../../bookings/presentation/components/booking-status-tag.vue';

const { t, locale } = useI18n();
const router = useRouter();
const store = useOverviewStore();

const query = ref('');
const suggestions = ref([]);
const search = ref(null);
const isMac = /Mac|iPhone|iPad/.test(navigator.platform);

/**
 * Updates the suggestions for the typed text.
 * @param {{query: string}} event - AutoComplete search event.
 */
const complete = (event) => {
  suggestions.value = store.searchBookings(event.query);
};

/**
 * Opens the chosen booking and clears the search.
 * @param {{value: Object}} event - AutoComplete selection event.
 */
const openBooking = (event) => {
  query.value = '';
  router.push({
    name: 'bookings-booking-detail',
    params: { id: event.value.id },
  });
};

/**
 * Focuses the search with Ctrl+K or ⌘K.
 * @param {KeyboardEvent} event - Key event.
 */
const focusSearch = (event) => {
  if (event.key.toLowerCase() === 'k' && (event.metaKey || event.ctrlKey)) {
    event.preventDefault();
    search.value?.$el.querySelector('input')?.focus();
  }
};

onMounted(() => window.addEventListener('keydown', focusSearch));
onBeforeUnmount(() => window.removeEventListener('keydown', focusSearch));
</script>

<template>
  <pv-icon-field class="w-full md:w-18rem">
    <pv-input-icon class="pi pi-search z-1" />
    <pv-auto-complete
      ref="search"
      v-model="query"
      :suggestions="suggestions"
      option-label="guestName"
      :placeholder="
        t('overview.booking-search.placeholder', {
          shortcut: isMac ? '⌘K' : 'Ctrl+K',
        })
      "
      :aria-label="t('overview.booking-search.label')"
      :empty-search-message="t('overview.booking-search.empty')"
      :delay="150"
      size="small"
      input-class="w-full pl-5"
      fluid
      @complete="complete"
      @option-select="openBooking"
    >
      <template #option="{ option }">
        <span
          class="flex align-items-center justify-content-between gap-3 w-full"
        >
          <span class="flex flex-column min-w-0">
            <span class="font-semibold">{{ option.guestName }}</span>
            <span class="text-sm text-color-secondary"
              ><span class="font-mono">{{ option.code }}</span> ·
              {{
                formatDayRange(option.checkInDate, option.checkOutDate, locale)
              }}</span
            >
          </span>
          <booking-status-tag :status="option.status" />
        </span>
      </template>
    </pv-auto-complete>
  </pv-icon-field>
</template>
