// src/rooms/presentation/components/booking-controlled-dialog/booking-controlled-dialog.component.ts
import { Component, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MAT_DIALOG_DATA, MatDialogModule } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { formatDayRange } from '../../../../shared/presentation/calendar-format';
import { MessageComponent } from '../../../../shared/presentation/components/message/message.component';
import { I18nService } from '../../../../shared/presentation/i18n.service';
import { RoomAssignment } from '../../../domain/model/room-assignment.entity';
import { Room } from '../../../domain/model/room.entity';

/** Data of the booking-controlled dialog. */
export interface BookingControlledDialogData {
  room: Room;
  roomAssignment: RoomAssignment;
}

/**
 * Explains that a booking controls a room day, so its status changes from the booking.
 */
@Component({
  selector: 'app-booking-controlled-dialog',
  imports: [
    MatButtonModule,
    MatDialogModule,
    MatIconModule,
    RouterLink,
    MessageComponent,
  ],
  template: `
    <h2 mat-dialog-title>
      {{ i18n.t('rooms.booking-controlled-dialog.title') }}
    </h2>
    <mat-dialog-content>
      <div class="flex flex-column gap-3">
        <app-message severity="warn" icon="lock">
          <div class="flex flex-column gap-1">
            <span class="font-semibold">{{
              i18n.t('rooms.booking-controlled-dialog.summary', {
                status: i18n.t(
                  'rooms.rooms-terms.day-statuses.' + data.roomAssignment.status
                ),
              })
            }}</span>
            <span>{{
              i18n.t('rooms.booking-controlled-dialog.detail', {
                number: data.room.number,
                code: data.roomAssignment.bookingCode,
                dates: formatDayRange(
                  data.roomAssignment.startDate,
                  data.roomAssignment.endDate,
                  i18n.locale()
                ),
              })
            }}</span>
          </div>
        </app-message>
        <p class="m-0 line-height-3 text-color-secondary">
          {{ i18n.t('rooms.booking-controlled-dialog.help') }}
        </p>
      </div>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-stroked-button mat-dialog-close>
        {{ i18n.t('rooms.booking-controlled-dialog.close') }}
      </button>
      <a
        mat-flat-button
        cdkFocusInitial
        mat-dialog-close
        [routerLink]="['/bookings', data.roomAssignment.bookingId]"
      >
        {{ i18n.t('rooms.booking-controlled-dialog.open-booking') }}
        <mat-icon iconPositionEnd>arrow_forward</mat-icon>
      </a>
    </mat-dialog-actions>
  `,
})
export class BookingControlledDialogComponent {
  protected readonly i18n = inject(I18nService);
  protected readonly data =
    inject<BookingControlledDialogData>(MAT_DIALOG_DATA);
  protected readonly formatDayRange = formatDayRange;
}

// src/rooms/presentation/components/booking-controlled-dialog.vue
<script setup>
import { useI18n } from 'vue-i18n';
import { formatDayRange } from '../../../shared/presentation/calendar-format.js';

defineProps({
  room: { type: Object, required: true },
  roomAssignment: { type: Object, required: true },
});
const visible = defineModel('visible', { type: Boolean });

const { t, locale } = useI18n();
</script>

<template>
  <pv-dialog
    v-model:visible="visible"
    modal
    :header="t('rooms.booking-controlled-dialog.title')"
    :draggable="false"
    class="w-full mx-3"
    style="max-width: 32rem"
  >
    <div class="flex flex-column gap-3">
      <pv-message severity="warn" icon="pi pi-lock">
        <div class="flex flex-column gap-1">
          <span class="font-semibold">{{
            t('rooms.booking-controlled-dialog.summary', {
              status: t(
                `rooms.rooms-terms.day-statuses.${roomAssignment.status}`,
              ),
            })
          }}</span>
          <span>{{
            t('rooms.booking-controlled-dialog.detail', {
              number: room.number,
              code: roomAssignment.bookingCode,
              dates: formatDayRange(
                roomAssignment.startDate,
                roomAssignment.endDate,
                locale,
              ),
            })
          }}</span>
        </div>
      </pv-message>
      <p class="m-0 line-height-3 text-color-secondary">
        {{ t('rooms.booking-controlled-dialog.help') }}
      </p>
    </div>
    <template #footer>
      <pv-button
        :label="t('rooms.booking-controlled-dialog.close')"
        severity="secondary"
        outlined
        rounded
        @click="visible = false"
      />
      <router-link
        v-slot="{ navigate }"
        :to="{
          name: 'bookings-booking-detail',
          params: { id: roomAssignment.bookingId },
        }"
        custom
      >
        <pv-button
          :label="t('rooms.booking-controlled-dialog.open-booking')"
          icon="pi pi-arrow-right"
          icon-pos="right"
          rounded
          autofocus
          @click="navigate"
        />
      </router-link>
    </template>
  </pv-dialog>
</template>
