// src/bookings/presentation/components/bookings-layout/bookings-layout.component.ts
import {
  Component,
  computed,
  contentChild,
  inject,
  input,
} from '@angular/core';
import { Router } from '@angular/router';
import { AccessControlStore } from '../../../../access-control/application/access-control.store';
import { RoomsStore } from '../../../../rooms/application/rooms.store';
import { ContextLayoutComponent } from '../../../../shared/presentation/components/context-layout/context-layout.component';
import { LayoutBodyDirective } from '../../../../shared/presentation/components/context-layout/layout-body.directive';
import { I18nService } from '../../../../shared/presentation/i18n.service';
import { BookingsStore } from '../../../application/bookings.store';

/**
 * Bookings workspace layout: header with the property selector and the view's actions,
 * and the loading, error, and empty states of the bookings data.
 *
 * Views project their actions with `layoutActions` and their body with `<ng-template layoutBody>`.
 */
@Component({
  selector: 'app-bookings-layout',
  imports: [ContextLayoutComponent],
  template: `
    <app-context-layout
      [title]="title() || i18n.t('bookings.bookings-layout.title')"
      [properties]="roomsStore.properties()"
      [currentPropertyId]="roomsStore.currentPropertyId()"
      [propertyLabel]="i18n.t('bookings.bookings-layout.property')"
      [propertyDisabled]="store.saving()"
      [noProperties]="noProperties()"
      [noPropertiesMessage]="
        i18n.t('bookings.bookings-terms.errors.no-properties')
      "
      [failed]="loadErrors()"
      [connectionMessage]="i18n.t('bookings.bookings-terms.errors.connection')"
      [retryLabel]="i18n.t('bookings.bookings-layout.retry')"
      [loaded]="bookingsDataLoaded()"
      [loadingLabel]="i18n.t('bookings.bookings-layout.loading')"
      [body]="body()?.template"
      (propertyChange)="changeProperty($event)"
      (retry)="retry()"
    >
      <ng-container ngProjectAs="[layoutActions]"
        ><ng-content select="[layoutActions]"
      /></ng-container>
    </app-context-layout>
  `,
})
export class BookingsLayoutComponent {
  protected readonly i18n = inject(I18nService);
  protected readonly store = inject(BookingsStore);
  protected readonly roomsStore = inject(RoomsStore);
  private readonly accessControlStore = inject(AccessControlStore);
  private readonly router = inject(Router);

  /** Workspace title; the bookings title by default. */
  readonly title = input('');
  protected readonly body = contentChild(LayoutBodyDirective);

  protected readonly noProperties = computed(
    () =>
      this.roomsStore.propertiesLoaded() &&
      !this.roomsStore.properties().length,
  );
  /** Bookings need the property's rooms, rates, and operational statuses to price and place stays. */
  protected readonly bookingsDataLoaded = computed(
    () =>
      this.store.bookingsLoaded() &&
      this.store.paymentsLoaded() &&
      this.accessControlStore.credentialsLoaded() &&
      this.roomsStore.roomTypesLoaded() &&
      this.roomsStore.roomsLoaded() &&
      this.roomsStore.statusPeriodsLoaded() &&
      this.roomsStore.ratePlansLoaded() &&
      this.roomsStore.dailyRatesLoaded(),
  );
  protected readonly loadErrors = computed(
    () => !!(this.store.errors().length || this.roomsStore.errors().length),
  );

  constructor() {
    if (!this.roomsStore.propertiesLoaded()) this.roomsStore.fetchProperties();
  }

  /**
   * Returns to the booking list and loads the selected property's bookings.
   * @param propertyId - The ID of the selected property.
   */
  protected async changeProperty(propertyId: number): Promise<void> {
    await this.router.navigate(['/bookings']);
    this.roomsStore.selectProperty(propertyId);
  }

  /** Retries loading the properties or the current property's bookings and rooms. */
  protected retry(): void {
    if (!this.roomsStore.propertiesLoaded()) {
      this.roomsStore.fetchProperties();
      return;
    }
    this.roomsStore.selectProperty(this.roomsStore.currentPropertyId());
    this.store.fetchBookings();
  }
}

// src/bookings/presentation/components/bookings-layout.vue
<script setup>
import { computed, onMounted, toRefs } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRouter } from 'vue-router';
import useBookingsStore from '../../application/bookings.store.js';
import useRoomsStore from '../../../rooms/application/rooms.store.js';
import useAccessControlStore from '../../../access-control/application/access-control.store.js';
import SidebarToggle from '../../../shared/presentation/components/sidebar-toggle.vue';

const props = defineProps({
  title: { type: String, default: '' },
});

const { t } = useI18n();
const router = useRouter();
const store = useBookingsStore();
const roomsStore = useRoomsStore();
const accessControlStore = useAccessControlStore();
const { bookingsLoaded, paymentsLoaded, errors, saving } = toRefs(store);
const {
  properties,
  propertiesLoaded,
  currentPropertyId,
  roomTypesLoaded,
  roomsLoaded,
  statusPeriodsLoaded,
  ratePlansLoaded,
  dailyRatesLoaded,
} = toRefs(roomsStore);
const { fetchBookings } = store;
const { fetchProperties, selectProperty } = roomsStore;

const noProperties = computed(
  () => propertiesLoaded.value && !properties.value.length,
);
// Bookings need the property's rooms, rates, and operational statuses to price and place stays.
const bookingsDataLoaded = computed(
  () =>
    bookingsLoaded.value &&
    paymentsLoaded.value &&
    accessControlStore.credentialsLoaded &&
    roomTypesLoaded.value &&
    roomsLoaded.value &&
    statusPeriodsLoaded.value &&
    ratePlansLoaded.value &&
    dailyRatesLoaded.value,
);
const loadErrors = computed(
  () => errors.value.length || roomsStore.errors.length,
);

onMounted(() => {
  if (!roomsStore.propertiesLoaded) fetchProperties();
});

/**
 * Returns to the booking list and loads the selected property's bookings.
 * @param {number} propertyId - The ID of the selected property.
 */
const changeProperty = async (propertyId) => {
  await router.push({ name: 'bookings-list' });
  selectProperty(propertyId);
};

/**
 * Retries loading the properties or the current property's bookings and rooms.
 */
const retry = () => {
  if (!propertiesLoaded.value) {
    fetchProperties();
    return;
  }
  selectProperty(currentPropertyId.value);
  fetchBookings();
};
</script>

<template>
  <div class="flex flex-column">
    <header
      class="sticky top-0 z-2 flex flex-wrap align-items-center gap-2 px-3 md:px-5 py-2 md:h-4rem surface-card border-bottom-1 surface-border"
    >
      <sidebar-toggle />
      <pv-divider layout="vertical" class="h-1rem min-h-0 p-0 mx-1 my-0" />
      <h1
        class="m-0 mr-auto text-xl font-semibold tracking-tight white-space-nowrap overflow-hidden text-overflow-ellipsis"
      >
        {{ props.title || t('bookings.bookings-layout.title') }}
      </h1>
      <pv-select
        :model-value="currentPropertyId"
        :options="properties"
        option-label="name"
        option-value="id"
        :aria-label="t('bookings.bookings-layout.property')"
        :disabled="saving"
        size="small"
        class="flex-order-1 md:flex-order-0 w-full md:w-14rem"
        @update:model-value="changeProperty"
      >
        <template #value="{ value }">
          <span class="flex align-items-center gap-2">
            <i class="pi pi-building text-color-secondary" aria-hidden="true" />
            <span
              class="font-medium white-space-nowrap overflow-hidden text-overflow-ellipsis"
              >{{
                properties.find((property) => property.id === value)?.name ??
                '—'
              }}</span
            >
          </span>
        </template>
      </pv-select>
      <slot name="actions" />
    </header>

    <div class="flex flex-column gap-4 p-3 md:px-5 md:pt-4 md:pb-5">
      <pv-message v-if="noProperties" severity="warn" icon="pi pi-info-circle">
        {{ t('bookings.bookings-terms.errors.no-properties') }}
      </pv-message>
      <pv-message
        v-else-if="loadErrors && !bookingsDataLoaded"
        severity="error"
        icon="pi pi-exclamation-circle"
      >
        <div
          class="flex flex-column sm:flex-row sm:align-items-center justify-content-between gap-3"
        >
          <span>{{ t('bookings.bookings-terms.errors.connection') }}</span>
          <pv-button
            :label="t('bookings.bookings-layout.retry')"
            icon="pi pi-refresh"
            severity="danger"
            size="small"
            @click="retry"
          />
        </div>
      </pv-message>
      <div
        v-else-if="!bookingsDataLoaded"
        class="flex flex-column align-items-center gap-3 py-8 text-color-secondary"
        role="status"
      >
        <pv-progress-spinner
          :stroke-width="4"
          class="w-3rem h-3rem"
          aria-hidden="true"
        />
        <span>{{ t('bookings.bookings-layout.loading') }}</span>
      </div>
      <slot v-else />
    </div>
  </div>
</template>
