// src/bookings/presentation/components/booking-status-tag.vue
<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

const props = defineProps({
  status: { type: String, required: true },
});

const { t } = useI18n();

const appearances = {
  pending: { icon: 'pi pi-clock', severity: 'warn' },
  confirmed: { icon: 'pi pi-calendar', severity: 'info' },
  'checked-in': { icon: 'pi pi-sign-in', severity: 'success' },
  'checked-out': { icon: 'pi pi-sign-out', severity: 'secondary' },
  cancelled: { icon: 'pi pi-times-circle', severity: 'danger' },
  'no-show': { icon: 'pi pi-user-minus', severity: 'secondary' },
};
const appearance = computed(
  () => appearances[props.status] ?? appearances.pending,
);
</script>

<template>
  <pv-tag
    :icon="appearance.icon"
    :severity="appearance.severity"
    :value="t(`bookings.bookings-terms.statuses.${status}`)"
    class="white-space-nowrap"
  />
</template>

// src/bookings/presentation/components/booking-status-tag/booking-status-tag.component.ts
import { Component, computed, inject, input } from '@angular/core';
import {
  StatusTagComponent,
  TagSeverity,
} from '../../../../shared/presentation/components/status-tag/status-tag.component';
import { I18nService } from '../../../../shared/presentation/i18n.service';
import { BookingStatus } from '../../../domain/model/booking.entity';

const appearances: Record<
  BookingStatus,
  { icon: string; severity: TagSeverity }
> = {
  pending: { icon: 'schedule', severity: 'warn' },
  confirmed: { icon: 'event', severity: 'info' },
  'checked-in': { icon: 'login', severity: 'success' },
  'checked-out': { icon: 'logout', severity: 'secondary' },
  cancelled: { icon: 'cancel', severity: 'danger' },
  'no-show': { icon: 'person_remove', severity: 'secondary' },
};

/** Tag with the icon and color of a booking status. */
@Component({
  selector: 'app-booking-status-tag',
  imports: [StatusTagComponent],
  template: `<app-status-tag
    [icon]="appearance().icon"
    [severity]="appearance().severity"
    [value]="i18n.t('bookings.bookings-terms.statuses.' + status())"
  />`,
})
export class BookingStatusTagComponent {
  protected readonly i18n = inject(I18nService);
  readonly status = input.required<BookingStatus>();
  protected readonly appearance = computed(
    () => appearances[this.status()] ?? appearances.pending,
  );
}
